import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import { FaBeer } from 'react-icons/fa';


export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
    <h1>lasdfghjn</h1>
    <FaBeer />
    {/* <Navbar /> */}
    </div>
  )
}
