import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import Intro from '../components/Intro';
import Contact from '../components/Contact';
import Footer from '../components/Footer';



export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
  
    <Navbar />
    <Intro />
    <Contact />
    <Footer />
    
    </div>
  )
}
